# Estética
FONT_NAME = "Arial"
FONT_SIZE = 12
FONT = (FONT_NAME, FONT_SIZE)
TREEVIEW_FONT_SIZE = 14
TREEVIEW_FONT = (FONT_NAME, TREEVIEW_FONT_SIZE)

# Padding
PADX = 10
PADY = 10
FRAME_PADY = 20
BOTTOM_FRAME_PADY = 10

# Colors
BUTTON_BG_COLOR = "#f0f0f0"
BUTTON_FG_COLOR = "#000000"
WINDOW_BG_COLOR = "#ffffff"

# Window sizes and resizable settings
MAIN_WINDOW_SIZE = "1400x600"
MAIN_WINDOW_RESIZABLE = (False, False)
CLIENT_CRUD_WINDOW_SIZE = "800x600"
CLIENT_CRUD_WINDOW_RESIZABLE = (False, False)
PAYMENT_CRUD_WINDOW_SIZE = "1000x600"
PAYMENT_CRUD_WINDOW_RESIZABLE = (False, False)

# Button styles
ADD_BUTTON_BG_COLOR = "#d4edda"
DELETE_BUTTON_BG_COLOR = "#f8d7da"
EDIT_BUTTON_BG_COLOR = "#fff3cd"
FILTER_BUTTON_BG_COLOR = "#d1ecf1"
TOGGLE_BUTTON_BG_COLOR = "#cce5ff"
SEND_REMINDER_BUTTON_BG_COLOR = "#d1ecf1"
FILTER_CLIENT_BUTTON_BG_COLOR = "#d1ecf1"
TOGGLE_PAID_BUTTON_BG_COLOR = "#cce5ff"
CLIENT_CRUD_BUTTON_BG_COLOR = "#d1ecf1"
PAYMENT_CRUD_BUTTON_BG_COLOR = "#d1ecf1"
REFRESH_BUTTON_BG_COLOR = "#d1ecf1"
